FROM python:3.11-slim

COPY . ./services
WORKDIR services

RUN pip3 install -r requirements.txt

EXPOSE ${MAIN_APP_PORT}

CMD ["uvicorn", "ml_service.flat_app:app", "--port", "1702", "--host", "0.0.0.0"]